version: "3.7"

# 10 Things to Consider When Planning Your Elasticsearch Project: https://ecmarchitect.com/archives/2015/07/27/4031
# Using Apache JMeter to Test Elasticsearch: https://ecmarchitect.com/archives/2014/09/02/3915
volumes:
    logstash: {}
    
    
services:
  logstash:
    image: docker.elastic.co/logstash/logstash:${ELASTIC_VERSION:-7.2}
    hostname: "{{.Node.Hostname}}-logstash"
    environment:
      - XPACK_MONITORING_ELASTICSEARCH_URL=http://elasticsearch:9200
      - XPACK_MONITORING_ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME:-elastic}
      - XPACK_MONITORING_ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD:-changeme}
    volumes:
      - logstash:/usr/share/logstash
    configs:
      - source: ls_pipelines_config
        target: /usr/share/logstash/config/pipelines.yml
      - source: ls_apicountryusers_config
        target: /usr/share/logstash/pipeline/APICountryUsers.conf
      - source: ls_jdbcfbactmembers_config
        target: /usr/share/logstash/pipeline/JDBCFBActMembers.conf
        
networks:
    traefik-publik:
      external: true

configs:
  ls_pipelines_config:
    file: $PWD/elk/logstash/pipelines.yml
  ls_apicountryusers_config:
    file: $PWD/elk/logstash/config/APICountryUsers.conf
  ls_jdbcfbactmembers_config:
    file: $PWD/elk/logstash/config/JDBCFBActMembers.conf

    
